### ISSUE TITLE
Prefix env variable with service provider

### ISSUE THREAD

**Issue by ghost** [cibuilds/chrome-extension#8]
`CLIENT_ID` -> `GOOGLE_CLIENT_ID`

**Comment by FelicianoTech** [comment]
Hey @kytwb, can you elaborate?

**Comment by ghost** [comment]
I don't remember why I struggle to guess it was the Google Client ID and thought prefixing would help, but after double checking, LGTM as it, not sure why I doubted. My bad 😅
